name: wmdi-data-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas
    - numpy
    - requests
    - langchain
    - langchain-openai
    - langchain-experimental
    - ipython 